apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django_hp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod 
spec:
  tls:
    - hosts:
        - devopsaz.fun 
      secretName: django_hp-secret
  rules:
    - host: devopsaz.fun
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django_hp-ingress
                port:
                  number: 80
