apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website-deployment
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: ghcr.io/fedorenko-m/app_t:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
