apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-hp
  namespace: django-hp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: my-django-hp
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-django-hp
        app.kubernetes.io/component: web
    spec:
      containers:
      - name: django-hp
        image: ghcr.io/fedorenko-m/app_t:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
