apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-hp
  namespace: django-hp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: djangoapp
  template:
    metadata:
      labels:
        app: djangoapp
    spec:
      containers:
      - name: django-hp
        image: docker.io/sh1zik/django_hp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
