apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-hp
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-django-hp
  template:
    metadata:
      labels:
        app: my-django-hp
    spec:
      containers:
      - name: my-django-hp
        image: docker.io/sh1zik/django_hp:latest
        ports:
        - containerPort: 8080
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: my-django-hp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: my-django-hp