apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-hp-ingress
  namespace: django-hp
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: devopsaz.fun
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: django-hp-service
            port:
              number: 80
