apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-hp-ingress
  namespace: django-hp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - "devopsaz.fun"
    secretName: tls-secret
  rules:
  - host: "devopsaz.fun"
    http:
      paths:
      - path: /
        backend:
          serviceName: django-hp-service
          servicePort: 80

