apiVersion: v1
kind: Service
metadata:
  name: django-hp-service
  namespace: web-app
spec:
  selector:
    app: djangoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
