apiVersion: v1
kind: Service
metadata:
  name: django-hp-service
  namespace: django-hp
  labels:
    app.kubernetes.io/name: django-hp-service
    app.kubernetes.io/component: web
spec:
  selector:
    app: django-hp-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
