apiVersion: v1
kind: Service
metadata:
  name: django-hp-service
  namespace: django-hp
spec:
  selector:
    app: django-hp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
