apiVersion: v2
name: my-djago-hp
description: Helm chart for deploy my django app
version: 0.1.0
appVersion: 1.0

ingress:
  enabled: true
  host: devopsaz.fun
  pathType: Prefix

webapp:
  enabled: true
  image:
    repository: docker.io/sh1zik/django_hp:latest 
    tag: latest
    pullPolicy: IfNotPresent
  service:
    enabled: true
    type: ClusterIP
    port: 80

maintainers:
- name: Sh1zik
  email: andriykolomiec218@gmail.com
