apiVersion: v2
name: my-djago_hp
description: Helm chart for deploy my django app
version: 0.1.0
appVersion: 1.0

dependencies:
- name: nginx-ingress
  version: 0.22.0
  repository: https://kubernetes.github.io/ingress-nginx

values:
  replicaCount: 3
  image:
    repository: docker.io/sh1zik/django_hp
    tag: latest
  ingress:
    host: devopsaz.fun
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod


maintainers:
- name: Sh1zik
  email: andriykolomiec218@gmail.com
