name: "Deploy app in k8s cluster"
on:
  workflow_dispatch:
  workflow_call:


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1

      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - run: az aks get-credentials --resource-group django_hp --name django-helpdesk

    - uses: azure/setup-helm@v3
      with:
        version: 'latest'
        token: ${{ secrets.TOKEN_GH }}
      id: install

    - name: Add nginx ingress

      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && helm repo update

    - name: Deploy Helm Chart

      run: |
        helm dependency build ./Helm/django && helm upgrade --install -n=django_hp app --namespace django_hp --create-namespace ./Helm/django
      env:
        KUBE_CONFIG: ~/.kube/config
