name: "Deploy app in k8s cluster"
on:
  workflow_dispatch:
  workflow_call:


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - run: az aks get-credentials --resource-group django_hp --name django-helpdesk

    - uses: azure/setup-helm@v3
      with:
        version: 'latest'
        token: ${{ secrets.TOKEN_GH }}
      id: install

    - name: Deploy Helm Chart

      run: |
        helm upgrade --install -n=django_hp django_hp ./Helm
      env:
        KUBE_CONFIG: ~/.kube/config
