name: "Deploy app in k8s cluster"
on:
  workflow_dispatch:
  workflow_call:


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1

      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - run: az aks get-credentials --resource-group django-helpdesk --name practice-aks-cluster

    - uses: azure/setup-helm@v3
      with:
        version: 'latest'
        token: ${{ secrets.TOKEN_GH }}
      id: install

    # - name: Add cert-manager
    #   run: |
    #     helm repo add jetstack https://charts.jetstack.io || true && \
    #     helm repo update || true && \
    #     helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.13.2  --set installCRDs=true || true

    - name: Add helm repo

      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx || true && \
        helm install ingress-nginx ingress-nginx/ingress-nginx --namespace django-hp --create-namespace \
        --set controller.defaultTLS.secret=some-tls-secret \
        --set controller.replicaCount=2 \
        --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
        --set controller.enableCustomResources=true \
        --set controller.enableTLSPassthrough=true \
        --set controller.healthStatus=true \
        --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux \
        --set controller.admissionWebhooks.patch.nodeSelector."beta\.kubernetes\.io/os"=linux \
        --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz || true

    - name: Deploy Helm Chart

      run: helm dependency build ./Helm/django  && helm upgrade --install -n=django-hp app --namespace django-hp --create-namespace ./Helm/django
      env:
        KUBE_CONFIG: ~/.kube/config
