name: "Deploy app in k8s cluster"
on:
  workflow_dispatch:
  workflow_call:


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1

      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - run: az aks get-credentials --resource-group django-helpdesk --name practice-aks-cluster

    - uses: azure/setup-helm@v3
      with:
        version: 'latest'
        token: ${{ secrets.TOKEN_GH }}
      id: install

    - name: Add cert-manager
      run: |
         helm repo add jetstack https://charts.jetstack.io && \
         helm repo update && \
         helm install cert-manager jetstack/cert-manager --version v1.13.2
      
    - name: Add helm repo
      
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx && \
        helm repo update && \
        helm install ingress-nginx ingress-nginx/ingress-nginx

    - name: Deploy Helm Chart

      run: |
        helm upgrade --install -n=django-hp app --namespace django-hp --create-namespace ./Helm/django
      env:
        KUBE_CONFIG: ~/.kube/config
