name: "Deploy app in k8s cluster"
on:
  workflow_dispatch:
  workflow_call:


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - run: az aks get-credentials --resource-group django_hp --name django-helpdesk


      - uses: Azure/k8s-set-context@v3
        with:
          kubeconfig: ~/.kube/config